# Site settings
name: David LaMartina
email: david@davidlamartina.com
#canonical_url: http://davidlamartina.com
keywords: "Software Engineer, Python, Javascript, C++, GIS, Web Development, Agile"
skills: "Software Developer in Loveland, CO"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/davidlamartina/

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 679DEC
  primary-rgb: "103, 157, 236"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
